license="${mod_license}"
issueTrackerURL="https://github.com/ThreeTAG/Palladium/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://squirrelcontrol.threetag.net/api/forge_updates/threetag-palladium"
displayURL="https://modrinth.com/project/threetag-palladium"
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="${mod_authors}"
description='''${mod_description}'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"