name: Build and Release Preview (1.21.10)

on:
  push:
    branches:
      - "1.21.10/dev"
    paths:
      - "src/**"

jobs:
  build:
    name: "Build and Release Previews"
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - run: chmod +x gradlew

      - name: Build Version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace --no-daemon

      - name: Setting mod version
        run: |
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^mod_id= >> $GITHUB_ENV
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^minecraft_version= >> $GITHUB_ENV

      - name: Get short commit hash
        id: vars
        run: echo "mod_version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Publish version
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: Palladium Preview ${{ env.mod_version }} for NeoForge ${{ env.minecraft_version }}
          version: ${{ env.mod_version }}+${{ env.minecraft_version }}
          modrinth-id: 92dtp3u1
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          changelog: "https://github.com/ThreeTAG/Palladium/compare/${{ github.event.before }}...${{ github.sha }}"
          loaders: |
            neoforge
          game-versions: |
            ${{ env.minecraft_version }}
          files: |
            build/libs/!(*-@(dev-shadow|sources|javadoc)).jar
          dependencies: |
            geckolib(optional){modrinth:8BmcQJ2H}{curseforge:388172}
            accessories(optional){modrinth:jtmvUHXj}{curseforge:938917}
